version: '3.7'

services:

  mongo_app:
    build:
      context: ./app/mongo_app
      dockerfile: Dockerfile
    ports:
      - "7007:7007"
    depends_on:
      - mongo
    networks:
      - my_net_1

  mongo:
    image: mongo
    container_name: mongo_db1
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - my_net_1


# вроде бы реально не требуется отдельная сетка, но пусть будет
networks:
  my_net_1:
    name: my_perfect_net
    driver: "bridge"
    external: false



